export { ConsumerBackend } from './src/service/consumer-backend';
export { ResourceProxy } from './src/domain/model/resource-proxy';
export { ResultPage } from './src/domain/model/result-page';
export { Type } from './src/domain/model/type';
export { Payload } from './src/domain/model/payload';
export { Property, PropertyInterface } from './src/domain/model/property';
export { Uri } from './src/domain/model/uri';
export { ResourceProxyRepository } from './src/domain/repository/resource-proxy-repository';
export { Paginator } from './src/domain/paginator/paginator';
export { LoadMorePaginator } from './src/domain/paginator/load-more-paginator';
